### PR TITLE
Test EVM EE with basic test case

### LINKED ISSUE #34: Generate a simpler test case than add11
The EVM EE fails to produce the correct post state root for the default test case (`add11`), and therefore I had to disable the evm test in CI (#32). Passing `add11` is a longer term task (highlighted requirements in #33). Before that we should nevertheless craft a few test cases manually and work our way up to `add11`. Initially we should avoid gas handling & `SSTORE` in the test cases to make things easier.

Similar to state tests the test cases should have a two pre accounts with balances and one with a bytecode. The bytecode should end with the `RETURN` statement, e.g. it should `ADD` two numbers and then `RETURN` the result. We also send along the expected return value as input to EE and the EE after executing bytecode checks the return value against expected value. It should also correctly perform the value transfer from sender to the contract.

### PR DESCRIPTION
**Pull request by s1na**
I set out to create a basic test case to run the evm EE and have it pass. To get there I had to fix a few other things to. Therefore this PR is a combination of a few changes:

- It adds a new relayer that generates scout config files for a test case similar to the `add11` state test. With the difference that instead of `SSTORE` it checks the expected value (sent to EE as part of block data) against value returned by evm code. Additionally the `postStateRoot` only takes value transfers into account, and no other state change (including metering).
- To achieve that it adds initial logic for `MSTORE8` and `RETURN` opcodes. They only consider the last byte of offset though, this needs to be fixed.
- Modifies `encodeAccount` to accept account's state root and code hash, instead of encoding the default values.
- It also re-adds `npm run evm` to CI
- It makes the EE inputs `codeHashes`, `bytecode` and `returnValue` mandatory, since we now have the token logic in a different file and don't need to maintain backwards-compatibility.

Fixes #34

### CODE REVIEW

File: assembly/evm.ts [hunk 1]
```diff
@@ -59,10 +61,36 @@ export function interpret(code: Uint8Array): void {
         // TODO:
         // store(position, value)
         break
+      case Opcodes.MStore8:
+        let offset = stackElements[stackTop - 1]
+        let val = stackElements[stackTop - 2]
+
+        // TODO: Consider whole offset, not only last byte
+        let offsetU8: u8 = offset[31]
```
Comment (hugo-dc) [inline assembly/evm.ts]: The offset is not being considered.

File: assembly/main.ts [hunk 2]
```diff
@@ -94,12 +94,9 @@ export function processBlock(preStateRoot: Uint8Array, blockData: Uint8Array): U
   // Instructions are flat-encoded
   let instructions = input_decoded.children[5].buffer // instructions
 
-  let codeHashes: RLPData[] = []
-  let bytecode: RLPData[] = []
-  if (input_decoded.children.length == 8) {
-    codeHashes = input_decoded.children[6].children // codeHashes
```
Comment (hugo-dc) [inline assembly/main.ts]: could we also remove the comments above (`//codeHashes... //instructions... etc`), since they're not really necessary and to maintain uniformity.

File: assembly/evm.ts [hunk 3]
```diff
@@ -16,7 +17,7 @@ export function interpret(code: Uint8Array): void {
   }
 
   const memorySize = 100
-  const memoryElementSize = 16
+  const memoryElementSize = 32
```
Comment (hugo-dc) [inline assembly/evm.ts]: `32` is the correct value.

Comment (s1na) [reply assembly/evm.ts]: Ok, thanks again for looking into this!

File: assembly/evm.ts (hunk 1 above)
Comment (s1na) [reply assembly/evm.ts]: Good catch!
